//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BrilhaMuito.SharedKernel.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Template {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Template() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BrilhaMuito.SharedKernel.Resources.Template", typeof(Template).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;pt-br&quot;&gt;
        ///  &lt;head&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot; /&gt;
        ///     &lt;meta charset=&quot;utf-8&quot;&gt;
        ///    &lt;title&gt;Bem-vindo, #name#!&lt;/title&gt;
        ///    &lt;style type=&quot;text/css&quot; rel=&quot;stylesheet&quot; media=&quot;all&quot;&gt;
        ///
        ///    
        ///    *:not(br):not(tr):not(html) {
        ///      font-family: Arial, &apos;Helvetica Neue&apos;, Helvetica, sans-serif;
        ///      box-sizing: border-box;
        ///    }
        ///    
        ///    body {
        ///      width: 100% !important;
        ///      height: 100%;
        ///      margin: 0;
        ///      line-height: 1.4; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string ForgotBody {
            get {
                return ResourceManager.GetString("ForgotBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recuperação de Senha.
        /// </summary>
        public static string ForgotSubject {
            get {
                return ResourceManager.GetString("ForgotSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string WelcomeMemberBody {
            get {
                return ResourceManager.GetString("WelcomeMemberBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seja bem-vindo #name#.
        /// </summary>
        public static string WelcomeMemberSubject {
            get {
                return ResourceManager.GetString("WelcomeMemberSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;!DOCTYPE html&gt;
        ///&lt;html lang=&quot;pt-br&quot;&gt;
        ///  &lt;head&gt;
        ///    &lt;meta name=&quot;viewport&quot; content=&quot;width=device-width, initial-scale=1.0&quot; /&gt;
        ///     &lt;meta charset=&quot;utf-8&quot;&gt;
        ///    &lt;title&gt;Bem-vindo, #name#!&lt;/title&gt;
        ///    &lt;style type=&quot;text/css&quot; rel=&quot;stylesheet&quot; media=&quot;all&quot;&gt;
        ///
        ///    
        ///    *:not(br):not(tr):not(html) {
        ///      font-family: Arial, &apos;Helvetica Neue&apos;, Helvetica, sans-serif;
        ///      box-sizing: border-box;
        ///    }
        ///    
        ///    body {
        ///      width: 100% !important;
        ///      height: 100%;
        ///      margin: 0;
        ///      line-height: 1.4; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string WelcomeUserBody {
            get {
                return ResourceManager.GetString("WelcomeUserBody", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seja bem-vindo #name#.
        /// </summary>
        public static string WelcomeUserSubject {
            get {
                return ResourceManager.GetString("WelcomeUserSubject", resourceCulture);
            }
        }
    }
}
